---
# Add all dependent roles, that should be executed before
# the content of this role. If this is an appliance
# there should always be atleast these 3 includes

# Change needed roles here
- name: download dependencies from galaxy
  shell: ansible-galaxy install {{ item }}
  args:
    creates: "{{ role_path }}/../{{ item }}"
  with_items:
  - uniqconsulting.firewall

- name: uniqconsulting.firewall
  include_role:
    name: uniqconsulting.firewall
  vars:
    firewall_open_ports:
    - port: 27017
      protocol: tcp
      source: "{{ item }}"
    - port: 27018
      protocol: tcp
      source: "{{ item }}"
    - port: 27019
      protocol: tcp
      source: "{{ item }}"
  with_items: "{{ mongodb_nodes }}"
    
- name: uniqconsulting.firewall
  include_role:
    name: uniqconsulting.firewall
  vars:
    firewall_open_ports:
    - port: 27017
      protocol: tcp
      source: "{{ item }}"
  with_items: "{{ mongodb_clients }}"

...